import type { Metadata } from "next";
import "./globals.css";
import 'remixicon/fonts/remixicon.css'
import { PrismicPreview } from '@prismicio/next'
import { repositoryName } from '@/prismicio'
import { Header } from "./ui/layout/header";
import { Footer } from "./ui/layout/footer";
import { SmoothScrolling } from "./ui/smooth_scrolling";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/tgj4zdp.css"/>
      </head>
      <body className="antialiased text-black text-base">
        <SmoothScrolling>
          <Header />
          {children}
          <Footer />
        </SmoothScrolling>
        <PrismicPreview repositoryName={repositoryName} />
      </body>
    </html>
  );
}
