// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  article_list: dynamic(() => import("./ArticleList")),
  experience: dynamic(() => import("./Experience")),
  image: dynamic(() => import("./Image")),
  lighthouse: dynamic(() => import("./Lighthouse")),
  skills: dynamic(() => import("./Skills")),
  slideshow: dynamic(() => import("./Slideshow")),
  text: dynamic(() => import("./Text")),
};
